language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

install:
  - composer self-update
  - composer install
  - composer require satooshi/php-coveralls --dev

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

matrix:
  allow_failures:
    - php: hhvm

after_script:
  - php vendor/bin/coveralls